---
dontChroot: false
timeout: 120
verbose: true

script:
  - "/usr/local/bin/umao-finalize-installed-customization"
  - "-/usr/local/bin/umao-fix-boot-root-cmdline"
  - "-/usr/local/bin/umao-apply-grub-branding"

i18n:
  name: "UmaOS post-install setup"
