---
dontChroot: false
timeout: 1800
verbose: true

script:
  - "/usr/local/bin/umao-fix-initcpio-preset"
  - "-/usr/local/bin/umao-driver-setup --yes --best-effort"

i18n:
  name: "Pre-initcpio system setup"
