# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
qmlSearch: both
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: true

requirements:
  check: []
  required: []

geoip:
  style: "none"

